name: Run Web Scraper

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dropbox sqlite3

    - name: Download Database File from Dropbox
      env:
        DROPBOX_ACCESS_TOKEN: ${{ secrets.DROPBOX_ACCESS_TOKEN }}
      run: |
        python - <<EOF
        import os
        import dropbox

        # Authenticate with Dropbox
        dbx = dropbox.Dropbox(os.getenv('DROPBOX_ACCESS_TOKEN'))

        # Download the file
        file_path = '/immodb.db'
        local_path = 'immodb.db'
        with open(local_path, 'wb') as f:
            metadata, res = dbx.files_download(path=file_path)
            f.write(res.content)

        EOF

    - name: Run scraper
      run: python scraper.py